feat: Добавь генераторы рандомных чисел
htmlacademy-javascript/397481-keksobooking-23 pull request #2
Opened 2021-05-29 12:57 UTC by AlexZaw

2021-05-29 16:39 UTC, ArtMan-8 requested changes

2021-05-29 16:39 UTC, ArtMan-8 commented on index.html
> +<script src="js/main.js"></script>
Лучше использовать относительные пути,
при размещении на сервере могут быть проблемы.

2021-05-29 16:39 UTC, ArtMan-8 commented on js/main.js
> +
Давай ещё подумаем,
1. Функции очень похожи, и отличаются только третьим параметром, может можно сделать его с аргументом по умолчанию.
2. При хорошей реализации не важно мин/макс на своих местах или нет, и будет работать без свопа.

2021-05-29 17:19 UTC, AlexZaw commented on index.html
> +<script src="js/main.js"></script>
Так это же и есть относительный путь. Или ты имеешь ввиду что нужно указать `./js/main.js` чтобы не возникло проблем с `PATH` ?

2021-05-29 17:33 UTC, ArtMan-8 commented on index.html
> +<script src="js/main.js"></script>
`./js/main.js` - да, вот так имею ввиду,

2021-05-31 05:44 UTC, merged

2021-05-31 05:44 UTC, ArtMan-8 commented on js/main.js
> +  if (min >= max) {
Будет правильно работать без этой проверки.

2021-05-31 07:53 UTC, AlexZaw commented on js/main.js
> +  if (min >= max) {
Хм, как? Если передать, например, отрицательный min, то в результат будут попадать и отрицательные числа и ноль.
Только если `decimalPlaces < 0` убрать, тут сам `toFixed` ошибку выдаст если что

2021-05-31 07:56 UTC, AlexZaw commented on js/main.js
> +  if (min >= max) {
> Будет правильно работать без этой проверки.

Хм, не пойму как :( Если передать, например, отрицательный min, то в результат будут попадать и отрицательные числа и ноль.
Только если decimalPlaces < 0 убрать, тут сам toFixed ошибку выдаст если что

2021-05-31 08:12 UTC, ArtMan-8 commented on js/main.js
> +  if (min >= max) {
Отрицательный `min` у тебя фильтруется выше, на 2й строке,
я конкретно про условие на 5й строке

2021-05-31 08:25 UTC, AlexZaw commented on js/main.js
> +  if (min >= max) {
В такой реализации как у меня сейчас, `getRandomNumber(3,1)` всегда возвращает 2. Я просто уже не смог ничего придумать и жду когда ты расскажешь как решить этот вопрос :)