Module4 task1
htmlacademy-javascript/397481-keksobooking-23 pull request #3
Opened 2021-06-06 09:18 UTC by AlexZaw

2021-06-06 14:37 UTC, ArtMan-8 requested changes

2021-06-06 14:37 UTC, ArtMan-8 commented on js/main.js
> +const OffersOptions = {
В перечислениях принято названия и ключи писать в единственном числе.

2021-06-06 14:37 UTC, ArtMan-8 commented on js/main.js
> +const OffersOptions = {
Возможно погорячился всё засунуть в один объект, но будет видно дальше.

2021-06-06 14:37 UTC, ArtMan-8 commented on js/main.js
> +  const result = decimalPlaces ?
С переносами обычно так пишется, операторы тернарника на новой строке
```
  const result = decimalPlaces
    ? (Math.random() * (upper - lower) + lower).toFixed(decimalPlaces) 
    : Math.floor(Math.random() * (upper - lower + 1) + lower);
```

2021-06-06 14:37 UTC, ArtMan-8 commented on js/main.js
> +const getRandomObjectMinMax = (obj) => getRandomNumber(obj.MIN, obj.MAX);
Не совсем понятна роль функции, она возвращает случайное число из диапазона.
Почему не использовать `getRandomNumber`.
К тому же завязываться на внутреннюю структуру какого-то объекта не есть хорошо в данном случае. Вдруг он изменится.

2021-06-06 14:37 UTC, ArtMan-8 commented on js/main.js
> +  adObj.offer.desciption = adObj.offer.title;
Выглядит как `хак`, попробуй сделать `нормально`.
Посмотри в сторону замыкания.

2021-06-06 14:37 UTC, ArtMan-8 commented on js/main.js
> +const getLocation = () => ({ lat: getRandomNumber(OffersOptions.LOCATION.LATITUDE.MIN, OffersOptions.LOCATION.LATITUDE.MAX, OffersOptions.LOCATION.PRECISSION), lng: getRandomNumber(OffersOptions.LOCA
Что за однострочник, ничего не понятно )

2021-06-06 14:37 UTC, ArtMan-8 commented on js/main.js
> +const createAd = (index) => {
По хорошему, функция не должен зависеть от аргументов.
В частности `getAvatar`.

Тут можно не мудрить особо.
Сделай готовый массив с аватарами и извлекай по одному.
Так же у тебя есть тасовщик массива, можно через него пропустить.

2021-06-06 14:37 UTC, ArtMan-8 commented on js/main.js
> +  return +result;
Используй явно приведение типов - `Number()`

2021-06-06 14:39 UTC, ArtMan-8 commented
В общем не плохо 👍
Но нужно доработать напильником )

2021-06-06 16:37 UTC, AlexZaw commented on js/main.js
> +const OffersOptions = {
> В перечислениях принято названия и ключи писать в единственном числе.

А по Б5 "Массивы названы существительными во множественном числе." именование ключей с массивами в единственном числе пройдет?

2021-06-06 16:40 UTC, ArtMan-8 commented on js/main.js
> +const OffersOptions = {
Если ключ для массива, то в множественном числе оставляй.

2021-06-06 16:41 UTC, AlexZaw commented on js/main.js
> +const getRandomObjectMinMax = (obj) => getRandomNumber(obj.MIN, obj.MAX);
Так это для борьбы с магическими числами, мы же не знаем, например, минимальное и максимальное количество комнат, вот эти значения и берутся из ключей объекта

2021-06-06 16:50 UTC, ArtMan-8 commented on js/main.js
> +const getRandomObjectMinMax = (obj) => getRandomNumber(obj.MIN, obj.MAX);
Это я понял, вопрос не про магические значение.
А про то, что привязываешься к структуре объекта.
А по факту просто обвёртка над `getRandomNumber`, почему туда сразу не передавать нужные мин/макс.

2021-06-06 16:55 UTC, AlexZaw commented on js/main.js
> +const getLocation = () => ({ lat: getRandomNumber(OffersOptions.LOCATION.LATITUDE.MIN, OffersOptions.LOCATION.LATITUDE.MAX, OffersOptions.LOCATION.PRECISSION), lng: getRandomNumber(OffersOptions.LOCA
какой именно? :)

2021-06-06 17:00 UTC, AlexZaw commented on js/main.js
> +const getRandomObjectMinMax = (obj) => getRandomNumber(obj.MIN, obj.MAX);
Просто не хотел раздувать код в самой функции создания объекта :) Кстати а какое-нибудь название у таких функций есть? Оно вроде и конструктор и не конструктор :)

2021-06-06 17:01 UTC, ArtMan-8 commented on js/main.js
> +const getLocation = () => ({ lat: getRandomNumber(OffersOptions.LOCATION.LATITUDE.MIN, OffersOptions.LOCATION.LATITUDE.MAX, OffersOptions.LOCATION.PRECISSION), lng: getRandomNumber(OffersOptions.LOCA
Этот - 300 символов в строке.
На уровне линтера/притера ограничивают до 80 символов обычно.
Иными словами, что бы строка умещалась на один экран, и не нужно было скролить.

2021-06-06 17:08 UTC, ArtMan-8 commented on js/main.js
> +const getRandomObjectMinMax = (obj) => getRandomNumber(obj.MIN, obj.MAX);
Не бойся писать больше, главное понятность.

2021-06-06 17:16 UTC, AlexZaw commented on js/main.js
> +const getLocation = () => ({ lat: getRandomNumber(OffersOptions.LOCATION.LATITUDE.MIN, OffersOptions.LOCATION.LATITUDE.MAX, OffersOptions.LOCATION.PRECISSION), lng: getRandomNumber(OffersOptions.LOCA
а это уже гитхаб так сделал у меня это вот так выглядит:
`
const getLocation = () => ({ lat: getRandomNumber(OfferOption.LOCATION.LATITUDE.MIN, OfferOption.LOCATION.LATITUDE.MAX, OfferOption.LOCATION.PRECISSION), lng: getRandomNumber(OfferOption.LOCATION.LONGITUDE.MIN, OfferOption.LOCATION.LONGITUDE.MAX, OfferOption.LOCATION.PRECISSION) });
`

2021-06-06 17:20 UTC, ArtMan-8 commented on js/main.js
> +const getLocation = () => ({ lat: getRandomNumber(OffersOptions.LOCATION.LATITUDE.MIN, OffersOptions.LOCATION.LATITUDE.MAX, OffersOptions.LOCATION.PRECISSION), lng: getRandomNumber(OffersOptions.LOCA
Одна строка ) может в редакторе перенос строк включён.
Ну и за счёт длииииных переменных растягивается
А нужно так. Не знаю, понятно ли будет.
```
const getLocation = () => ({
   lat: getRandomNumber(OfferOption.LOCATION.LATITUDE.MIN, OfferOption.LOCATION.LATITUDE.MAX, OfferOption.LOCATION.PRECISSION),
   lng: getRandomNumber(OfferOption.LOCATION.LONGITUDE.MIN, OfferOption.LOCATION.LONGITUDE.MAX, OfferOption.LOCATION.PRECISSION)
});
```

2021-06-06 18:29 UTC, AlexZaw commented on js/main.js
> +const getLocation = () => ({ lat: getRandomNumber(OffersOptions.LOCATION.LATITUDE.MIN, OffersOptions.LOCATION.LATITUDE.MAX, OffersOptions.LOCATION.PRECISSION), lng: getRandomNumber(OffersOptions.LOCA
ну это гитхаб постарался :), у меня вот так написано:
`
const getLocation = () => ({ lat: getRandomNumber(OfferOption.LOCATION.LATITUDE.MIN, OfferOption.LOCATION.LATITUDE.MAX, OfferOption.LOCATION.PRECISSION), lng: getRandomNumber(OfferOption.LOCATION.LONGITUDE.MIN, OfferOption.LOCATION.LONGITUDE.MAX, OfferOption.LOCATION.PRECISSION) });
`

2021-06-07 05:38 UTC, ArtMan-8 commented on js/main.js
> +    imageFullName = id < 10
Есть метод `padStart`, можно обойтись без условия.

2021-06-07 05:45 UTC, ArtMan-8 commented on js/main.js
> +const createAd = () => {
Всё ещё не то.

2021-06-07 05:47 UTC, ArtMan-8 commented on js/main.js
> +const similarAds = new Array(OfferOption.USER.MAX).fill(null).map(() =>
Если функция внутри `.map` применяется к каждому элементу,
то можно передать просто ссылку на функцию `.map(createAd)`

2021-06-07 07:42 UTC, AlexZaw commented on js/main.js
> +const createAd = () => {
ну я только так еще могу придумать, больше в голову ничего не идет :)
`
const getLocation = () => ({
  lat: getRandomNumber(OfferOption.LOCATION.LATITUDE.MIN,
    OfferOption.LOCATION.LATITUDE.MAX,
    OfferOption.LOCATION.PRECISSION),
  lng: getRandomNumber(OfferOption.LOCATION.LONGITUDE.MIN,
    OfferOption.LOCATION.LONGITUDE.MAX,
    OfferOption.LOCATION.PRECISSION),
});
`

2021-06-07 07:44 UTC, AlexZaw commented on js/main.js
> +const createAd = () => {
ну я только так еще могу придумать, больше в голову ничего не идет :)
```
const getLocation = () => ({
  lat: getRandomNumber(OfferOption.LOCATION.LATITUDE.MIN,
    OfferOption.LOCATION.LATITUDE.MAX,
    OfferOption.LOCATION.PRECISSION),
  lng: getRandomNumber(OfferOption.LOCATION.LONGITUDE.MIN,
    OfferOption.LOCATION.LONGITUDE.MAX,
    OfferOption.LOCATION.PRECISSION),
});
```

2021-06-07 07:49 UTC, ArtMan-8 commented on js/main.js
> +const createAd = () => {
Уже ближе, а как использовать будешь?
Нужен полный код )

2021-06-07 08:15 UTC, merged